gantry run \
  --task-name "test_simple_gantry" \
  --description "Run first SIMPLE test of gantry" \
  --workspace ai2/flex2 \
  --cluster   ai2/jupiter \
  --budget    ai2/oe-base \
  --priority  low \
  --weka=oe-training-default:/data/input/   \
  --timeout -1 \
  --beaker-image 'ai2/cuda12.8-dev-ubuntu22.04-torch2.6.0' \
  --venv 'base' \
  -- bash -c "echo hello && echo goodbye"