ROOT_DIR: .

seed: 0 # DO NOT CHANGE THIS.

exp_name: "main"

train:
  do: False
  model_path_or_name: "meta-llama/Meta-Llama-3-8B"
  out_directory: "models"

  wandb:
    do: False

test:
  do: True

