ROOT_DIR: .

seed: 0 # DO NOT CHANGE THIS.

exp_name: "pubmed"

num_proc: 1

train:
  do: True
  model_path_or_name: "meta-llama/Meta-Llama-3-8B"
  out_directory: "test_output_models"

  wandb:
    do: False


