ROOT_DIR: .

seed: 0 # DO NOT CHANGE THIS.

exp_name: "pubmed_100k_BS-64"
data_type: "pubmed"

num_proc: 1

train:
  do: True
  model_path_or_name: "meta-llama/Meta-Llama-3-8B"
  out_directory: "models"

  wandb:
    do: True
    project: "conditional_learning"
    group: ${data_type}
    name: ${exp_name}
    config:
      data_type: "pubmed"
      batch_size: 64
      num_instances: 100_000
    tags:
      - "data_type-pubmed"
      - "num_instances-100k"
      - "batch_size-64"

  save_model: True

  max_seq_len: 512

  training_args:
    per_device_train_batch_size: 1
    gradient_accumulation_steps: 16
    num_train_epochs: 1
    save_steps: 50
#    fp16: True
    bf16: True
    bf16_full_eval: True
    logging_steps: 2
    deepspeed: "configs/ds_config.json"


