ROOT_DIR: /root/ryanwang/phdbrainstorm

seed: 0 # DO NOT CHANGE THIS.

exp_name: "pubmed_orig"
data_type: "pubmed_orig"

num_proc: 128

train:
  do: True
  model_path_or_name: "meta-llama/Meta-Llama-3-8B"
  out_directory: "${ROOT_DIR}/data/${data_type}/out.jsonl"

  max_seq_len: 8192

