ROOT_DIR: /root/ryanwang/phdbrainstorm

seed: 0 # DO NOT CHANGE THIS.

exp_name: "pubmed_orig"
data_type: "pubmed_orig"

num_proc: 128

train:
  do: True
  tokenizer_name: "allenai/OLMo-2-1124-7B"

  out_directory: "${ROOT_DIR}/data/${data_type}/${train.tokenizer_name}"

  max_seq_len: 8192 # not used
